# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookReviewApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookReviewApp
pod 'Alamofire', '~> 5.1'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'

  target 'BookReviewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookReviewAppUITests' do
    # Pods for testing
  end

end

